service: cloudService

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: ap-southeast-1

functions:
  api:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
  greeting:
    handler: handler.greeting
    events:
      - http:
          path: /
          method: get
  sendMail:
    handler: handler.sendMail
    events:
      - http:
          path: sendMail
          method: get
  addMessage:
    handler: handler.addMessage
    events:
      - http:
          path: addMessage
          method: get